/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type FeatureExpeienceFragment = {
    latestYearData: ({
        total: number | null;
        completion: ({
            count: number | null;
            percentage: number | null;
        }) | null;
        buckets: (({
            type: ("never_heard" | "heard" | "used") | null;
            count: number | null;
            percentage: number | null;
        }) | null)[] | null;
    }) | null;
};
